[theme]
primaryColor = "#22d3ee"

background: linear-gradient(
    180deg,
    #dbeafe 0%,
    #bfdbfe 50%,
    #93c5fd 100%
);
secondaryBackgroundColor = "#16213e"

textColor = "#f8fafc"

font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
