[theme]
primaryColor = "#22d3ee"

secondaryBackgroundColor = "#1f2937"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true

enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
